feat: Adicionando relatório técnico
dcc-ufla/guia-do-tcc pull request #11
Opened 2023-01-22 01:08 UTC by ademarsj

Para resolver a issue #10 escrevi baseado no relatório de estágio e  adicionei as informações adicionais que o relatório técnico exige, junto com uma breve descrição de como preencher os capítulos.

Também adicionei no guia de relatório de estágio um breve aviso sobre o impeditivo de sua realização caso já esteja um profissional efetivado.

2023-02-06 23:24 UTC, paulojunior-ufla requested changes

2023-02-06 23:24 UTC, paulojunior-ufla commented on relatorio-estagio.md
> +**Atenção**
Colocar uma referência para essa afirmação (alguma norma ou resolução da UFLA, por exemplo).
Dar um destaque maior a essa informação, por exemplo, usando o recurso de citação (quotes) do Markdown. Exemplo:

> Esta é uma citação...

2023-02-06 23:24 UTC, paulojunior-ufla commented on relatorio-tecnico.md
> +O relatório de estágio se enquadra na definição de "Projeto orientado em sistemas de informação", na seção do PPC (Projeto Pedagógico do Curso) dos cursos de Bacharelado em Ciência da Computação [^1]
Relatório de estágio ou relatório técnico?

2023-02-06 23:24 UTC, paulojunior-ufla commented on relatorio-tecnico.md
> +Em geral, um relatório técnico é composto pelos seguintes capítulos: **Introdução**, **Referencial Teórico**, **Ferramentas e Tecnologias utilizadas**, **Requisitos do Software**, **Funcionalidades d
Fica com muitos capítulos assim. Sugiro resumir **Ferramentas e Tecnologias utilizadas**, **Requisitos do Software**, **Funcionalidades do Software** em apenas um capítulo denominado "Solução proposta". Dizer no texto que esse capítulo (Solução proposta) pode ser desmembrado em seções, tal qual as que você propôs.

Sobre a parte de avaliação, deixar claro para o aluno que é desejável, mas não obrigatória para que seu relatório seja aceito.

2023-02-06 23:24 UTC, paulojunior-ufla commented on relatorio-tecnico.md
> +## 4. Como posso escrever o "Referencial Teórico" de um Relatório Técnico?
Aqui acabou que você falou das ferramentas e tecnologias utilizadas e o capítulo "Ferramentas e tecnologias utilizadas" não foi descrito.

2023-02-06 23:24 UTC, paulojunior-ufla commented
@ademarsj, muito obrigado por sua contribuição. Achei incrível! Coloquei alguns comentários para melhoria do texto acima. Qualquer dúvida, estou à disposição.

2023-02-07 01:56 UTC, ademarsj commented on relatorio-tecnico.md
> +O relatório de estágio se enquadra na definição de "Projeto orientado em sistemas de informação", na seção do PPC (Projeto Pedagógico do Curso) dos cursos de Bacharelado em Ciência da Computação [^1]
Relatório técnico, será corrigido.

2023-02-07 02:32 UTC, ademarsj commented on relatorio-estagio.md
> +**Atenção**
As normas da UFLA mais pertinentes não encontrei, elas datam de 2009, e mesmo nas procuras pelo boletim interno não obtive sucesso, os resultados pararam em 2012. 
Estarei anexando outra legislação que consegui vincular as disposições do estágio.

2023-02-07 02:48 UTC, ademarsj commented on relatorio-tecnico.md
> +Em geral, um relatório técnico é composto pelos seguintes capítulos: **Introdução**, **Referencial Teórico**, **Ferramentas e Tecnologias utilizadas**, **Requisitos do Software**, **Funcionalidades d
Concordo, irei organizar de outra forma.

2023-02-07 02:56 UTC, ademarsj commented on relatorio-tecnico.md
> +## 4. Como posso escrever o "Referencial Teórico" de um Relatório Técnico?
Ok, será mencionado.

2023-02-07 02:58 UTC, ademarsj commented
@paulojunior-ufla  , realizei os commits com relação às alterações solicitadas.

2023-02-07 18:51 UTC, merged

2023-02-07 18:51 UTC, paulojunior-ufla commented
Muito obrigado @ademarsj. Suas contribuições foram "mergeadas" à _main_ deste repositório.